#!/usr/bin/env node
/**
 * Morning Brief Generator
 * Generates daily morning brief with weather, macro news, and tasks
 * Outputs to JSON for deployment to Slack DM
 */

const https = require('https');
const fs = require('fs');
const path = require('path');
const { execSync } = require('child_process');

const OUTPUT_FILE = process.argv[2] || '/tmp/morning-brief.json';
const ZIP_CODE = '11040'; // New Hyde Park, NY
const MEMORY_DIR = path.join(process.env.HOME, 'clawd', 'memory');
const TASK_MANAGER = path.join(process.env.HOME, 'clawd', 'task-manager');

// Get weather from wttr.in (text-based weather service)
async function getWeather() {
  return new Promise((resolve) => {
    https.get(`https://wttr.in/${ZIP_CODE}?format=3`, (res) => {
      let data = '';
      res.on('data', chunk => data += chunk);
      res.on('end', () => resolve(data.trim() || 'Weather unavailable'));
    }).on('error', () => resolve('Weather unavailable'));
  });
}

// Get macro news highlights from memory or generate placeholder
function getMacroNews() {
  const newsFile = path.join(MEMORY_DIR, 'macro-news.md');

  if (fs.existsSync(newsFile)) {
    const content = fs.readFileSync(newsFile, 'utf8');
    const lines = content.split('\n').filter(l => l.trim()).slice(0, 5);
    return lines.length > 0 ? lines.join('\n') : 'No macro news updates';
  }

  return 'No macro news updates - check X for latest';
}

// Get tasks for today
function getTodaysTasks() {
  try {
    const output = execSync(`cd ${TASK_MANAGER} && node cli.js list --status pending`, {
      encoding: 'utf8',
      timeout: 5000
    });

    const tasks = output.split('\n')
      .filter(line => line.startsWith('['))
      .slice(0, 8)
      .map(line => '• ' + line.replace(/^\[\d+\]\s+/, '').split('-')[0].trim())
      .join('\n');

    return tasks || '• No pending tasks';
  } catch (err) {
    return '• Unable to fetch tasks';
  }
}

// Get projects from memory
function getActiveProjects() {
  const projectsFile = path.join(MEMORY_DIR, 'active-projects.md');

  if (fs.existsSync(projectsFile)) {
    const content = fs.readFileSync(projectsFile, 'utf8');
    const lines = content.split('\n').filter(l => l.startsWith('-') || l.startsWith('*')).slice(0, 5);
    return lines.length > 0 ? lines.join('\n') : '• No active projects tracked';
  }

  return '• eBay Scanner automation\n• 21M Sports content pipeline\n• Task automation system';
}

// Generate the morning brief
async function generateBrief() {
  const weather = await getWeather();
  const macroNews = getMacroNews();
  const tasks = getTodaysTasks();
  const projects = getActiveProjects();
  const date = new Date().toLocaleDateString('en-US', {
    weekday: 'long',
    year: 'numeric',
    month: 'long',
    day: 'numeric'
  });

  const brief = `☀️ *Good Morning - ${date}*

📍 *Weather (New Hyde Park, NY)*
${weather}

📰 *Macro News*
${macroNews}

🎯 *Active Projects*
${projects}

✅ *Today's Scheduled Tasks*
${tasks}

---
_Generated by Jett at ${new Date().toLocaleTimeString()}_`;

  return brief;
}

// Main execution
(async () => {
  try {
    console.log('🌅 Generating morning brief...');

    const brief = await generateBrief();

    const output = {
      type: 'morning_brief',
      timestamp: new Date().toISOString(),
      content: brief,
      metadata: {
        zipCode: ZIP_CODE,
        generatedAt: new Date().toLocaleString()
      }
    };

    fs.writeFileSync(OUTPUT_FILE, JSON.stringify(output, null, 2));
    console.log(`✓ Morning brief saved to ${OUTPUT_FILE}`);
    console.log('\nPreview:');
    console.log(brief);

  } catch (error) {
    console.error('Error generating morning brief:', error.message);
    process.exit(1);
  }
})();
